version: '3'
networks:
  db:
services:
  postgres:
    container_name: yfood_db
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=yfood_db_dev
      - POSTGRES_USER=yfood_db@dev
      - POSTGRES_PASSWORD=yfood_db_dev
      - MAX_CONNECTIONS=300
    networks:
      - db
