
server:
  port: 8000
spring:
  resources:
    add-mappings: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/yfood_db_dev?currentSchema=yfood_db_dev
    username: yfood_db@dev
    password: yfood_db_dev
